<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE rule-manager [
<!ELEMENT rule-manager (custompackage-list*, fix-ruleset*, ruleset-list+, rule-list+)>
  <!ATTLIST rule-manager
  rulesets_title CDATA #REQUIRED
>
  <!ELEMENT custompackage-list (package*)>
  <!ELEMENT package (#PCDATA)>
  <!ATTLIST package
    id CDATA #REQUIRED
    name CDATA #REQUIRED
    description CDATA #REQUIRED
    creationdate CDATA #REQUIRED
    modifydate CDATA #IMPLIED
>
  <!ELEMENT fix-ruleset (field*)>
  <!ATTLIST field
  id CDATA #REQUIRED
  value CDATA #IMPLIED
>
  <!ELEMENT ruleset-list (ruleset+)>
  <!ELEMENT ruleset (ruleset-name+, ruleset-description+, ruleset-component*)>
  <!ATTLIST ruleset
  id CDATA #REQUIRED
    is_short_circuit CDATA #REQUIRED
    type CDATA #REQUIRED
    sid CDATA #IMPLIED
    extend CDATA #IMPLIED
>
  <!ELEMENT ruleset-name (#PCDATA)>
  <!ELEMENT ruleset-description (#PCDATA)>
  <!ELEMENT ruleset-component (name+, description+, priority+)>
  <!ATTLIST ruleset-component
  id CDATA #REQUIRED
    type CDATA #REQUIRED
>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT description (#PCDATA)>
  <!ELEMENT priority (#PCDATA)>
  <!ELEMENT rule-list (rule+)>
  <!ELEMENT rule (rule-name+, rule-description+, rule-action+, rule-type+)>
  <!ATTLIST rule
  id CDATA #REQUIRED
    isactive CDATA #REQUIRED
    sid CDATA #IMPLIED
    extend CDATA #IMPLIED
>
  <!ELEMENT rule-name (#PCDATA)>
  <!ELEMENT rule-description (#PCDATA)>
  <!ELEMENT rule-action (#PCDATA)>
  <!ELEMENT rule-type (#PCDATA)>
]>
<rule-manager rulesets_title="Generic Payroll Ruleset">
    <custompackage-list/>
    <fix-ruleset>
        <field id="UTE Time in Time Pairs" value="NewBubbleSheetRuleset"/>
        <field id="RIA Time in Time Pairs" value="TimePairsRuleset"/>        
        <field id="Time in Duration" value="NewTimeSheetRuleset"/>
        <field id="Time in Detail" value="NewDailyEditsRuleset"/>
        <field id="Start Of Day" value="NewStartOfDayRuleset"/>
        <field id="Payroll Summary" value="PayrollSummaryRuleset"/>
        <field id="Default Shift" value="DefaultShiftRuleset"/>
        <field id="Super Timesheet" value="NewTimeSheetRuleset"/>
        <field id="Public Holiday" value="HolidayEligibilityRuleset"/>
        <field id="Misc. Check Request" value="RequestMiscCheckRuleset"/>
        <field id="Employee Total Hours" value="PayrollSummaryRuleset"/>
        <field id="Read Clock Data" value="ReadClockDataRuleset"/>
        <field id="Recalculate Payroll" value="RecalculatePayrollRuleset"/>
        <field id="Mass Update Employee Org Powerpay" value="MassUpdateEmpOrgCreateRuleset"/>
        <!-- RIA Custom Time and Attendance Rulesets -->
        <field id="RIA TimeSheet Time Pairs Custom Ruleset" value="TimeSheetTimePairsCustomRuleset"/>
        <field id="RIA TimeSheet Duration Custom Ruleset" value="TimeSheetDurationCustomRuleset"/>
        <field id="RIA Payroll Summary Custom Ruleset" value="PayrollSummaryCustomRuleset"/>
        <field id="RIA TimeSheet Detail Custom Ruleset" value="TimeSheetDetailCustomRuleset"/>
        <field id="RIA Labor Distribution Ruleset" value="LaborDistributionCustomRuleset"/>
        <field id="RIA View Employee Total Hours Custom Ruleset" value="ViewEmployeeTotalHoursCustomRuleset"/>
        <field id="RIA TimeSheet Detailed Duration Custom Ruleset" value="TimeSheetDetailedDurationCustomRuleset"/>
    </fix-ruleset>
    <ruleset-list>
        <!-- *********************************************************** -->
        <!--                       NEW DAILY EDITS RULESET               -->
        <!-- *********************************************************** -->
        <!-- DO NOT MODIFY THIS SYSTEM RULESET                           -->
        <!-- *********************************************************** -->
        <!-- Following ruleset is invoked from the Daily Edits module -->
        <ruleset id="$$$NewDailyEditsRuleset" is_short_circuit="True" type="Private">
            <ruleset-name>$$$NewDailyEditsRuleset</ruleset-name>
            <ruleset-description>System ruleset for Daily Edits</ruleset-description>
            <ruleset-component id="RestoreHiddenSystemCodesRule" type="Rule">
                  <name>RestoreHiddenSystemCodesRule</name>
                  <description>The rule restores records that were hidden from the screen</description>
                  <priority>1</priority>
            </ruleset-component>
            <ruleset-component id="RunRulesIfManualCalcRuleset" type="Ruleset">
                  <name>RunRulesIfManualCalcRuleset</name>
                  <description>RunRulesIfManualCalcRuleset</description>
                  <priority>2</priority>
            </ruleset-component>
            <ruleset-component id="ManualCalcRule" type="Rule">
                  <name>ManualCalcRule</name>
                  <description>ManualCalcRule</description>
                  <priority>3</priority>
            </ruleset-component>
            <ruleset-component id="NewDailyEditsRuleset" type="Ruleset">
                  <name>NewDailyEditsRuleset</name>
                  <description>NewDailyEditsRuleset</description>
                  <priority>4</priority>
            </ruleset-component>
        </ruleset>
        <!-- *********************************************************** -->
        <!--                       TIME PAIRS RULESET               -->
        <!-- *********************************************************** -->
        <!-- DO NOT MODIFY THIS SYSTEM RULESET                           -->
        <!-- *********************************************************** -->
        <!-- Following ruleset is invoked from the Daily Edits module -->
        <ruleset id="$$$TimePairsRuleset" is_short_circuit="True" type="Private">
            <ruleset-name>$$$TimePairsRuleset</ruleset-name>
            <ruleset-description>System ruleset for Time Pair</ruleset-description>
            <ruleset-component id="RestoreHiddenSystemCodesRule" type="Rule">
                  <name>RestoreHiddenSystemCodesRule</name>
                  <description>The rule restores records that were hidden from the screen</description>
                  <priority>1</priority>
            </ruleset-component>            
            <ruleset-component id="RunRulesIfManualCalcRuleset" type="Ruleset">
                  <name>RunRulesIfManualCalcRuleset</name>
                  <description>RunRulesIfManualCalcRuleset</description>
                  <priority>2</priority>
            </ruleset-component>
            <ruleset-component id="ManualCalcRule" type="Rule">
                  <name>ManualCalcRule</name>
                  <description>ManualCalcRule</description>
                  <priority>3</priority>
            </ruleset-component>
            <ruleset-component id="TimePairsRuleset" type="Ruleset">
                  <name>TimePairsRuleset</name>
                  <description>TimePairsRuleset</description>
                  <priority>4</priority>
            </ruleset-component>

        </ruleset>        
        <!-- *********************************************************** -->
        <!--                OVERTIME FORECAST RULESET                    -->
        <!-- *********************************************************** -->
                <!-- DO NOT MODIFY THIS SYSTEM RULESET                           -->
        <!-- *********************************************************** -->
        <!-- Following ruleset is invoked from the TimeSheet module -->
        <ruleset id="$$$OvertimeForecastRuleset" is_short_circuit="True" type="Private">
            <ruleset-name>$$$OvertimeForecastRuleset</ruleset-name>
            <ruleset-description>System ruleset for Overtime Forecast</ruleset-description>
            <ruleset-component id="OvertimeForecastRuleset" type="Ruleset">
                  <name>OvertimeForecastRuleset</name>
                  <description>OvertimeForecastRuleset</description>
                  <priority>1</priority>
            </ruleset-component>
        </ruleset>
        <!-- *********************************************************** -->
        <!--                 NEW START OF DAY RULESET                    -->
        <!-- *********************************************************** -->
        <!-- DO NOT MODIFY THIS SYSTEM RULESET                           -->
        <!-- *********************************************************** -->
        <ruleset id="$$$NewStartOfDayRuleset" is_short_circuit="True" type="Private">
            <ruleset-name>$$$NewStartOfDayRuleset</ruleset-name>
            <ruleset-description>System ruleset for Start of Day</ruleset-description>
            <ruleset-component id="NewStartOfDayRuleset" type="Ruleset">
                  <name>NewStartOfDayRuleset</name>
                  <description>NewStartOfDayRuleset</description>
                  <priority>1</priority>
            </ruleset-component>
        </ruleset>
        <!-- *********************************************************** -->
        <!--                   READ CLOCK DATA RULESET                   -->
        <!-- *********************************************************** -->
        <!-- DO NOT MODIFY THIS SYSTEM RULESET                           -->
        <!-- *********************************************************** -->
        <ruleset id="$$$ReadClockDataRuleset" is_short_circuit="True" type="Private">
            <ruleset-name>$$$ReadClockDataRuleset</ruleset-name>
            <ruleset-description>System ruleset for Read Clock Data</ruleset-description>
            <ruleset-component id="ReadClockDataRuleset" type="Ruleset">
                  <name>ReadClockDataRuleset</name>
                  <description>ReadClockDataRuleset</description>
                  <priority>1</priority>
            </ruleset-component>
        </ruleset>
        <!-- *********************************************************** -->
        <!--                  RECALCULATE PAYROLL RULESET                -->
        <!-- *********************************************************** -->
        <!-- DO NOT MODIFY THIS SYSTEM RULESET                           -->
        <!-- *********************************************************** -->
        <!-- Following ruleset is invoked from the RecalculatePayroll module -->
        <ruleset id="$$$RecalculatePayrollRuleset" is_short_circuit="True" type="Private">
            <ruleset-name>$$$RecalculatePayrollRuleset</ruleset-name>
            <ruleset-description>System ruleset for Recalculate Payroll</ruleset-description>
            <ruleset-component id="RunRulesIfManualCalcRuleset" type="Ruleset">
                  <name>RunRulesIfManualCalcRuleset</name>
                  <description>RunRulesIfManualCalcRuleset</description>
                  <priority>1</priority>
            </ruleset-component>
            <ruleset-component id="ResetPayrollRecalcStatusRule" type="Rule">
                  <name>ResetPayrollRecalcStatusRule</name>
                  <description>ResetPayrollRecalcStatusRule</description>
                  <priority>2</priority>
            </ruleset-component>
            <ruleset-component id="ManualCalcRule" type="Rule">
                  <name>ManualCalcRule</name>
                  <description>ManualCalcRule</description>
                  <priority>3</priority>
            </ruleset-component>
            <ruleset-component id="RecalculatePayrollRuleset" type="Ruleset">
                  <name>RecalculatePayrollRuleset</name>
                  <description>RecalculatePayrollRuleset</description>
                  <priority>4</priority>
            </ruleset-component>
        </ruleset>
        <!-- *********************************************************** -->
        <!--                  REPROCESS CLOCK DATA RULESET               -->
        <!-- *********************************************************** -->
        <!-- DO NOT MODIFY THIS SYSTEM RULESET                           -->
        <!-- *********************************************************** -->
        <ruleset id="$$$ReprocessClockDataRuleset" is_short_circuit="True" type="Private">
            <ruleset-name>$$$ReprocessClockDataRuleset</ruleset-name>
            <ruleset-description>System ruleset for Reprocess Clock Data</ruleset-description>
          <!-- no ruleset components are required for this ruleset. -->
        </ruleset>
        <!-- *********************************************************** -->
        <!--               NEW TIME SHEET RULESET                        -->
        <!-- *********************************************************** -->
        <!-- DO NOT MODIFY THIS SYSTEM RULESET                           -->
        <!-- *********************************************************** -->
        <ruleset id="$$$NewTimeSheetRuleset" is_short_circuit="True" type="Private">
            <ruleset-name>$$$NewTimeSheetRuleset</ruleset-name>
            <ruleset-description>System ruleset for Time Sheet</ruleset-description>
            <ruleset-component id="RestoreHiddenSystemCodesRule" type="Rule">
                  <name>RestoreHiddenSystemCodesRule</name>
                  <description>The rule restores records that were hidden from the screen</description>
                  <priority>1</priority>
            </ruleset-component>            
            <ruleset-component id="RunRulesIfManualCalcRuleset" type="Ruleset">
                  <name>RunRulesIfManualCalcRuleset</name>
                  <description>RunRulesIfManualCalcRuleset</description>
                  <priority>2</priority>
            </ruleset-component>
            <ruleset-component id="ManualCalcRule" type="Rule">
                  <name>ManualCalcRule</name>
                  <description>ManualCalcRule</description>
                  <priority>3</priority>
            </ruleset-component>
            <ruleset-component id="NewTimeSheetRuleset" type="Ruleset">
                  <name>NewTimeSheetRuleset</name>
                  <description>NewTimeSheetRuleset</description>
                  <priority>4</priority>
            </ruleset-component>
        </ruleset>
        <!-- *********************************************************** -->
        <!--               NEW BUBBLE SHEET RULESET                      -->
        <!-- *********************************************************** -->
        <!-- DO NOT MODIFY THIS SYSTEM RULESET                           -->
        <!-- *********************************************************** -->
        <ruleset id="$$$NewBubbleSheetRuleset" is_short_circuit="True" type="Private">
            <ruleset-name>$$$NewBubbleSheetRuleset</ruleset-name>
            <ruleset-description>System ruleset for Bubble Sheet</ruleset-description>
            <ruleset-component id="RestoreHiddenSystemCodesRule" type="Rule">
                  <name>RestoreHiddenSystemCodesRule</name>
                  <description>The rule restores records that were hidden from the screen</description>
                  <priority>1</priority>
            </ruleset-component>            
            <ruleset-component id="UpdatePayrollFieldsRule" type="Rule">
                <name>UpdatePayrollFieldsRule</name>
                <description>UpdatePayrollFieldsRule</description>
                <priority>2</priority>
            </ruleset-component>
            <ruleset-component id="RunRulesIfManualCalcRuleset" type="Ruleset">
                <name>RunRulesIfManualCalcRuleset</name>
                <description>RunRulesIfManualCalcRuleset</description>
                <priority>3</priority>
            </ruleset-component>
            <ruleset-component id="ManualCalcRule" type="Rule">
                <name>ManualCalcRule</name>
                <description>ManualCalcRule</description>
                <priority>4</priority>
            </ruleset-component>
            <ruleset-component id="NewBubbleSheetRuleset" type="Ruleset">
                <name>NewBubbleSheetRuleset</name>
                <description>NewBubbleSheetRuleset</description>
                <priority>5</priority>
            </ruleset-component>
        </ruleset>
        <!-- *********************************************************** -->
        <!--              PAYROLL SUMMARY RULESET                        -->
        <!-- *********************************************************** -->
        <!-- DO NOT MODIFY THIS SYSTEM RULESET                           -->
        <!-- *********************************************************** -->
        <ruleset id="$$$PayrollSummaryRuleset" is_short_circuit="True" type="Private">
            <ruleset-name>$$$PayrollSummaryRuleset</ruleset-name>
            <ruleset-description>System ruleset for Payroll Summary</ruleset-description>
            <ruleset-component id="UpdatePayrollFieldsRule" type="Rule">
                <name>UpdatePayrollFieldsRule</name>
                <description>UpdatePayrollFieldsRule</description>
                <priority>1</priority>
            </ruleset-component>
            <ruleset-component id="RunRulesIfManualCalcRuleset" type="Ruleset">
                <name>RunRulesIfManualCalcRuleset</name>
                <description>RunRulesIfManualCalcRuleset</description>
                <priority>2</priority>
            </ruleset-component>
            <ruleset-component id="ManualCalcRule" type="Rule">
                <name>ManualCalcRule</name>
                <description>ManualCalcRule</description>
                <priority>3</priority>
            </ruleset-component>
            <ruleset-component id="PayrollSummaryRuleset" type="Ruleset">
                <name>PayrollSummaryRuleset</name>
                <description>PayrollSummaryRuleset</description>
                <priority>4</priority>
            </ruleset-component>
        </ruleset>
        <!-- *********************************************************** -->
        <!--                DEFAULT SHIFT RULESET                        -->
        <!-- *********************************************************** -->
        <!-- DO NOT MODIFY THIS SYSTEM RULESET                           -->
        <!-- *********************************************************** -->
        <ruleset id="$$$DefaultShiftRuleset" is_short_circuit="True" type="Private">
            <ruleset-name>$$$DefaultShiftRuleset</ruleset-name>
            <ruleset-description>System ruleset for Default Shift</ruleset-description>
            <ruleset-component id="DefaultShiftRuleset" type="Ruleset">
                <name>DefaultShiftRuleset</name>
                <description>DefaultShiftRuleset</description>
                <priority>1</priority>
            </ruleset-component>
        </ruleset>
        <!-- *********************************************************** -->
        <!--                REQUEST MISC CHECK RULESET                    -->
        <!-- *********************************************************** -->
        <!-- DO NOT MODIFY THIS SYSTEM RULESET                           -->
        <!-- *********************************************************** -->
        <ruleset id="$$$RequestMiscCheckRuleset" is_short_circuit="True" type="Private">
            <ruleset-name>$$$RequestMiscCheckRuleset</ruleset-name>
            <ruleset-description>System ruleset for Request Misc Check</ruleset-description>
            <ruleset-component id="RequestMiscCheckRuleset" type="Ruleset">
                <name>RequestMiscCheckRuleset</name>
                <description>RequestMiscCheckRuleset</description>
                <priority>1</priority>
            </ruleset-component>
        </ruleset>
        <!-- *********************************************************** -->
        <!--                NEW DAILY EDITS WF RULESET                   -->
        <!-- *********************************************************** -->
        <!-- DO NOT MODIFY THIS SYSTEM RULESET                           -->
        <!-- *********************************************************** -->
        <!-- Following ruleset is invoked from the Daily Edits module via the submit to workflow button -->
        <ruleset id="$$$NewDailyEditsWFRuleset" is_short_circuit="True" type="Private">
            <ruleset-name>$$$NewDailyEditsWFRuleset</ruleset-name>
            <ruleset-description>System ruleset for Daily Edits Workflow</ruleset-description>
            <ruleset-component id="RunRulesIfManualCalcRuleset" type="Ruleset">
                <name>RunRulesIfManualCalcRuleset</name>
                <description>RunRulesIfManualCalcRuleset</description>
                <priority>1</priority>
            </ruleset-component>
            <ruleset-component id="ManualCalcRule" type="Rule">
                <name>ManualCalcRule</name>
                <description>ManualCalcRule</description>
                <priority>2</priority>
            </ruleset-component>
            <ruleset-component id="NewDailyEditsWFRuleset" type="Ruleset">
                <name>NewDailyEditsWFRuleset</name>
                <description>NewDailyEditsWFRuleset</description>
                <priority>3</priority>
            </ruleset-component>
        </ruleset>
        <!-- *********************************************************** -->
        <!--                PAYROLL SUMMARY WF RULESET                   -->
        <!-- *********************************************************** -->
        <!-- DO NOT MODIFY THIS SYSTEM RULESET                           -->
        <!-- *********************************************************** -->
        <!-- Following ruleset is invoked from the Payroll Summary module via the submit to workflow button -->
        <ruleset id="$$$PayrollSummaryWFRuleset" is_short_circuit="True" type="Private">
            <ruleset-name>$$$PayrollSummaryWFRuleset</ruleset-name>
            <ruleset-description>System ruleset for Payroll Summary Workflow</ruleset-description>
			<ruleset-component id="AdjustOverlapLaborAfterRoundingAllRule" type="Ruleset">
                <name>AdjustOverlapLaborAfterRoundingAllRule</name>
                <description>AdjustOverlapLaborAfterRoundingAllRule</description>
                <priority>5</priority>
            </ruleset-component>
            <ruleset-component id="UpdatePayrollFieldsRule" type="Rule">
                <name>UpdatePayrollFieldsRule</name>
                <description>UpdatePayrollFieldsRule</description>
                <priority>1</priority>
            </ruleset-component>
            <ruleset-component id="RunRulesIfManualCalcRuleset" type="Ruleset">
                <name>RunRulesIfManualCalcRuleset</name>
                <description>RunRulesIfManualCalcRuleset</description>
                <priority>2</priority>
            </ruleset-component>
            <ruleset-component id="ManualCalcRule" type="Rule">
                <name>ManualCalcRule</name>
                <description>ManualCalcRule</description>
                <priority>3</priority>
            </ruleset-component>
            <ruleset-component id="PayrollSummaryWFRuleset" type="Ruleset">
                <name>PayrollSummaryWFRuleset</name>
                <description>PayrollSummaryWFRuleset</description>
                <priority>4</priority>
            </ruleset-component>
        </ruleset>
        <!-- *********************************************************** -->
        <!--                NEW BUBBLE SHEET WF RULESET                  -->
        <!-- *********************************************************** -->
        <!-- DO NOT MODIFY THIS SYSTEM RULESET                           -->
        <!-- *********************************************************** -->
        <!-- Following ruleset is invoked from the Bubblesheet module via the submit to workflow button -->
        <ruleset id="$$$NewBubbleSheetWFRuleset" is_short_circuit="True" type="Private">
            <ruleset-name>$$$NewBubbleSheetWFRuleset</ruleset-name>
            <ruleset-description>System ruleset for Bubble Sheet Workflow</ruleset-description>
            <ruleset-component id="UpdatePayrollFieldsRule" type="Rule">
                <name>UpdatePayrollFieldsRule</name>
                <description>UpdatePayrollFieldsRule</description>
                <priority>1</priority>
            </ruleset-component>
            <ruleset-component id="RunRulesIfManualCalcRuleset" type="Ruleset">
                <name>RunRulesIfManualCalcRuleset</name>
                <description>RunRulesIfManualCalcRuleset</description>
                <priority>2</priority>
            </ruleset-component>
            <ruleset-component id="ManualCalcRule" type="Rule">
                <name>ManualCalcRule</name>
                <description>ManualCalcRule</description>
                <priority>3</priority>
            </ruleset-component>
            <ruleset-component id="NewBubbleSheetWFRuleset" type="Ruleset">
                <name>NewBubbleSheetWFRuleset</name>
                <description>NewBubbleSheetWFRuleset</description>
                <priority>4</priority>
            </ruleset-component>
        </ruleset>
        <!-- *********************************************************** -->
        <!--               NEW TIME SHEET WF RULESET                     -->
        <!-- *********************************************************** -->
        <!-- DO NOT MODIFY THIS SYSTEM RULESET                           -->
        <!-- *********************************************************** -->
        <!-- Following ruleset is invoked from the Timesheet modules via the submit to workflow button -->
        <ruleset id="$$$NewTimeSheetWFRuleset" is_short_circuit="True" type="Private">
            <ruleset-name>$$$NewTimeSheetWFRuleset</ruleset-name>
            <ruleset-description>System ruleset for Time Sheet Workflow</ruleset-description>
            <ruleset-component id="RunRulesIfManualCalcRuleset" type="Ruleset">
                <name>RunRulesIfManualCalcRuleset</name>
                <description>RunRulesIfManualCalcRuleset</description>
                <priority>1</priority>
            </ruleset-component>
            <ruleset-component id="ManualCalcRule" type="Rule">
                <name>ManualCalcRule</name>
                <description>ManualCalcRule</description>
                <priority>2</priority>
            </ruleset-component>
            <ruleset-component id="NewTimeSheetWFRuleset" type="Ruleset">
                <name>NewTimeSheetWFRuleset</name>
                <description>NewTimeSheetWFRuleset</description>
                <priority>3</priority>
            </ruleset-component>
        </ruleset>
        <!-- **************************************************************** -->
        <!--               NEW MASS UPDATE EMP ORGANIZATION CREATE RULESET    -->
        <!-- **************************************************************** -->
        <!-- DO NOT MODIFY THIS SYSTEM RULESET                           -->
        <!-- *********************************************************** -->
        <!-- Following ruleset is invoked from the Employee Registration module for Employee Mass Update screen -->
        <ruleset id="$$$MassUpdateEmpOrgCreateRuleset" is_short_circuit="True" type="Private">
            <ruleset-name>$$$MassUpdateEmpOrgCreateRuleset</ruleset-name>
            <ruleset-description>System ruleset for Mass Update Employee Organization Create</ruleset-description>
            <ruleset-component id="MassUpdateEmpOrgCreateRuleset" type="Ruleset">
                <name>MassUpdateEmpOrgCreateRuleset</name>
                <description>MassUpdateEmpOrgCreateRuleset</description>
                <priority>1</priority>
            </ruleset-component>
        </ruleset>
        <!-- *********************************************************** -->
        <!--               STANDARD RULESET BELOW                        -->
        <!-- *********************************************************** -->
        <ruleset id="NewDailyEditsWFRuleset" is_short_circuit="False" sid="" type="Public">
            <ruleset-name>Daily Edits WF Ruleset(New)</ruleset-name>
            <ruleset-description>processes employee time information coming from the daily edits screen</ruleset-description>
            <ruleset-component id="NewDailyEditsRuleset" type="Ruleset">
                <name>Daily Edits Ruleset(New)</name>
                <description>displays employee information in the daily edits screen</description>
                <priority>1</priority>
            </ruleset-component>
			<ruleset-component id="OvertimeEntitlementRule" type="Ruleset">
                <name>OvertimeEntitlementRule</name>
                <description>displays employee information in the daily edits screen</description>
                <priority>2</priority>
            </ruleset-component>
        </ruleset>
        <ruleset id="PayrollSummaryWFRuleset" is_short_circuit="False" sid="" type="Public">
            <ruleset-name>PayrollSummaryWFRuleset</ruleset-name>
            <ruleset-description>processes employee time information coming from the payroll summary screen</ruleset-description>
            <ruleset-component id="PayrollSummaryRuleset" type="Ruleset">
                <name>PayrollSummaryRuleset</name>
                <description>PayrollSummaryRuleset</description>